CREATE DATABASE HotelDBMS1;
SHOW DATABASES;

 USE HotelDBMS1;
 SELECT * FROM hotel;
 SELECT * FROM RoomType;
 SELECT * FROM Room;
 SELECT * FROM Guest;
 SELECT * FROM EmployeeTableType;
 SELECT * FROM Employees;
 
 